apiVersion: v1
kind: Service
metadata:
  name: pattern-extractor-svc
spec:
  type: ClusterIP
  selector:
    app: pattern-extractor
  ports:
    - protocol: TCP
      port: 8000  # Porta que será exposta pelo serviço
      targetPort: 8000  # Porta do contêiner a ser direcionada
